# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hltv.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HltvWindow(object):
    def setupUi(self, HltvWindow):
        HltvWindow.setObjectName("HltvWindow")
        HltvWindow.resize(500, 317)
        HltvWindow.setMinimumSize(QtCore.QSize(500, 317))
        HltvWindow.setMaximumSize(QtCore.QSize(500, 317))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        HltvWindow.setFont(font)
        HltvWindow.setStyleSheet("background-color: rgb(5, 0, 35);")
        HltvWindow.setIconSize(QtCore.QSize(24, 24))
        HltvWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        HltvWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(HltvWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.event_number = QtWidgets.QLineEdit(self.centralwidget)
        self.event_number.setGeometry(QtCore.QRect(10, 140, 241, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.event_number.setFont(font)
        self.event_number.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.event_number.setMouseTracking(True)
        self.event_number.setStyleSheet("background-color: white;\n"
"border: 3px solid #3e6e9f;\n"
"border-radius: 15;\n"
"color: black;")
        self.event_number.setAlignment(QtCore.Qt.AlignCenter)
        self.event_number.setObjectName("event_number")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(260, 140, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("QPushButton {\n"
"background-color: rgb(62, 110, 159);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(62, 110, 159);\n"
"border-radius: 25px;\n"
"border: 5px solid  rgb(5, 0, 35);\n"
"color:white;\n"
"}R")
        self.pushButton_start.setObjectName("pushButton_start")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 230, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(124, 170, 236, 255), stop:1 rgba(135, 135, 135, 255));\n"
"    \n"
"}")
        self.progressBar.setMinimum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-1, -1, 501, 131))
        self.frame_2.setStyleSheet("background-color: rgb(62, 110, 159);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(116, 10, 301, 111))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(65)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.basement = QtWidgets.QLabel(self.centralwidget)
        self.basement.setGeometry(QtCore.QRect(-20, 280, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.basement.setFont(font)
        self.basement.setStyleSheet("color: rgb(255, 255, 255);")
        self.basement.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.basement.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.basement.setObjectName("basement")
        self.loading_info = QtWidgets.QLabel(self.centralwidget)
        self.loading_info.setGeometry(QtCore.QRect(140, 280, 351, 31))
        self.loading_info.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.loading_info.setAlignment(QtCore.Qt.AlignCenter)
        self.loading_info.setObjectName("loading_info")
        HltvWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(HltvWindow)
        QtCore.QMetaObject.connectSlotsByName(HltvWindow)

    def retranslateUi(self, HltvWindow):
        _translate = QtCore.QCoreApplication.translate
        HltvWindow.setWindowTitle(_translate("HltvWindow", "HLTV - PARSING"))
        self.pushButton_start.setText(_translate("HltvWindow", "СТАРТ"))
        self.label.setText(_translate("HltvWindow", "HLTV"))
        self.basement.setText(_translate("HltvWindow", "@BY MITROFANOV A.D"))
        self.loading_info.setText(_translate("HltvWindow", "loading_info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HltvWindow = QtWidgets.QMainWindow()
    ui = Ui_HltvWindow()
    ui.setupUi(HltvWindow)
    HltvWindow.show()
    sys.exit(app.exec_())
